# Copyright (c) 2026 Yuancheng Li
# SPDX-License-Identifier: Apache-2.0

CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_GLIBCXX_LIBCPP=y
CONFIG_SPI=y
CONFIG_DISPLAY=y
CONFIG_LOG=y

# Adjust heap and main stack size to accommodate the rendering buffers.
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=16384
